#pragma once

#include <Windows.h>
#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <cmath>
#include <cstring>
#include <ctime>
#include "Vector3D.h"
#include "Matrix4x4.h"
#include "InputSystem.h"
#include "Cube.h"
#include "Sphere.h"
#include "GraphicsEngine.h"
#include "RenderSystem.h"
#include "ImGui/imgui.h"
#include "ImGui/backends/imgui_impl_dx11.h"
#include "ImGui/backends/imgui_impl_win32.h"
#include "UIManager.h"
#include <algorithm>
#include "TextureManager.h"
#include "Texture.h"
#include "MeshManager.h"
#include "Mesh.h"
#include "ShaderLibrary.h"
#include "ShaderNames.h"
#include "SceneEditor.h"
#include "SceneBuilder.h" 
#include "SceneSerializer.h"
#include "PhysicsCube.h"
#include "PhysicsPlane.h"
#include "PhysicsComponent.h"
#include "PhysicsSystem.h"
#include "MeshComponent.h"
#include "BoxColliderComponent.h"
#include "BaseComponentSystem.h" 
#include "InputListener.h"
#include "Capsule.h"
#include <reactphysics3d/reactphysics3d.h>
#include <string>
#include <vector>
#include <memory>
#include <functional>
#include <unordered_map>
#include <sstream>
#include <iostream>
#include <chrono>
#include "Debug.h"
